### ISSUE TITLE
void Function error

### ISSUE THREAD

**Issue by NjiruClinton** [codingbbq/mentors_social_app#1]
@codingbbq help on the mentors_social_app/lib/pages/mentors.dart line 63

```
onChanged: (Filter newValue) {
                setState(() {
                  _value = newValue;
                });
              },
```

error on the (Filter newValue) : _The argument type 'void Function(Filter)' can't be assigned to the parameter type 'void Function(Filter?)?'._

**Comment by faizanMayo786** [comment]
You will have to use the null check operator:

```
onChanged: (Filter? newValue) {
                setState(() {
                  _value = newValue!;
                });
              },
```

**Comment by faizanMayo786** [comment]
I suggest you to Upgrade your flutter SDK and project then it might go away

**Comment by NjiruClinton** [comment]
This worked. Thanks. am using _Flutter 2.10.0-1.0.pre.324_
